// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Masters.MastersContext
{
    public partial interface IMastersContextProcedures
    {
        Task<List<sp_get_agent_ms_detail_by_idResult>> sp_get_agent_ms_detail_by_idAsync(string agentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_agent_ms_docResult>> sp_get_agent_ms_docAsync(string agent_id, string agent_type_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_company_branch_listResult>> sp_get_company_branch_listAsync(string company_id, string NIK, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_credit_sourceResult>> sp_get_credit_sourceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_customer_sourceResult>> sp_get_customer_sourceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_customer_typeResult>> sp_get_customer_typeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_employee_surcodeResult>> sp_get_employee_surcodeAsync(string NIKsurveryorcode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_evaluationResult>> sp_get_evaluationAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_hirarki_menu_by_userResult>> sp_get_hirarki_menu_by_userAsync(string NIK, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_industry_typeResult>> sp_get_industry_typeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_locationResult>> sp_get_locationAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_location_byidResult>> sp_get_location_byidAsync(int? locationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_marital_statusResult>> sp_get_marital_statusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_monthly_other_installmentResult>> sp_get_monthly_other_installmentAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_msreferencetype_refnameResult>> sp_get_msreferencetype_refnameAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_ownership_proofResult>> sp_get_ownership_proofAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_BPKBReceiverResult>> sp_get_pagination_BPKBReceiverAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_BPKBTypeOfBureauNecessityResult>> sp_get_pagination_BPKBTypeOfBureauNecessityAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_lookup_agentResult>> sp_get_pagination_lookup_agentAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_lookup_bankResult>> sp_get_pagination_lookup_bankAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_lookup_incentive_codeResult>> sp_get_pagination_lookup_incentive_codeAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_master_agent_msResult>> sp_get_pagination_master_agent_msAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_pagination_npp_dealer_bank_accountResult>> sp_get_pagination_npp_dealer_bank_accountAsync(string SearchTerm, OutputParameter<int?> PageIndex, OutputParameter<double?> PageSize, OutputParameter<int?> TotalPages, OutputParameter<double?> RecordCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_professionResult>> sp_get_professionAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_relationshipResult>> sp_get_relationshipAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_residence_statusResult>> sp_get_residence_statusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_sourceResult>> sp_get_sourceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_insert_agentResult>> sp_insert_agentAsync(string BranchID, string AgentID, string TipePerantara, string AgentName, string InsentifID, string Address, string City, string Phone, string HP, string Pekerjaan, int? IdentitasID, string NoIdentitas, string BankID, bool? IsActive, bool? IsNPWP, string TipeNPWP, string NoNPWP, string NamaNPWP, string AlamatNPWP, string reference, string doc_perjanjian_kerja_sama_name, string doc_perjanjian_kerja_sama_path, string doc_surat_rekomendasi_kacab_name, string doc_surat_rekomendasi_kacab_path, string doc_ktp_name, string doc_ktp_path, string doc_buku_tabungan_name, string doc_buku_tabungan_path, string doc_npwp_name, string doc_npwp_path, string doc_foto_bersama_mh_kacab_name, string doc_foto_bersama_mh_kacab_path, string Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_update_agentResult>> sp_update_agentAsync(string BranchID, string AgentID, string TipePerantara, string AgentName, string InsentifID, string Address, string City, string Phone, string HP, string Pekerjaan, int? IdentitasID, string NoIdentitas, string BankID, bool? IsActive, bool? IsNPWP, string TipeNPWP, string NoNPWP, string NamaNPWP, string AlamatNPWP, string reference, string doc_perjanjian_kerja_sama_name, string doc_perjanjian_kerja_sama_path, string doc_surat_rekomendasi_kacab_name, string doc_surat_rekomendasi_kacab_path, string doc_ktp_name, string doc_ktp_path, string doc_buku_tabungan_name, string doc_buku_tabungan_path, string doc_npwp_name, string doc_npwp_path, string doc_foto_bersama_mh_kacab_name, string doc_foto_bersama_mh_kacab_path, string Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
