// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsAgentDummyHns
    {
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public string Pt { get; set; }
        public string BranchId { get; set; }
        public string BankId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Hp { get; set; }
        public int? IdentitasId { get; set; }
        public string NoIdentitas { get; set; }
        public bool? IsActive { get; set; }
        public string UsrCrt { get; set; }
        public DateTime? DtmCrt { get; set; }
        public string UsrUpd { get; set; }
        public DateTime? DtmUpd { get; set; }
        public string TipePerantara { get; set; }
        public string Status { get; set; }
        public string ApproveBy { get; set; }
        public DateTime? ApproveDate { get; set; }
        public Guid Rowguid { get; set; }
        public string Nik { get; set; }
        public string AgentKoor { get; set; }
        public string NikagentKoor { get; set; }
        public string TipeNpwp { get; set; }
        public string NoNpwp { get; set; }
        public string NamaNpwp { get; set; }
        public string AlamatNpwp { get; set; }
        public string TipeAgent { get; set; }
        public string AgentInduk { get; set; }
        public string NikagentInduk { get; set; }
        public decimal? Pkpkumulatif { get; set; }
        public string InsentifId { get; set; }
        public string AgentIndukId { get; set; }
        public string PhoneCodeArea { get; set; }
        public string ReferensiJabatanId { get; set; }
        public bool? IsFreeText { get; set; }
        public string Nikreferensi { get; set; }
        public string NamaReferensi { get; set; }
        public string Pekerjaan { get; set; }
        public string Npplama { get; set; }
        public bool? IsNpwp { get; set; }
        public string DocPerjanjianKerjaSamaName { get; set; }
        public string DocPerjanjianKerjaSamaPath { get; set; }
        public string DocSuratRekomendasiKacabName { get; set; }
        public string DocSuratRekomendasiKacabPath { get; set; }
        public string DocKtpName { get; set; }
        public string DocKtpPath { get; set; }
        public string DocBukuTabunganName { get; set; }
        public string DocBukuTabunganPath { get; set; }
        public string DocNpwpName { get; set; }
        public string DocNpwpPath { get; set; }
        public string DocFotoBersamaMhKacabName { get; set; }
        public string DocFotoBersamaMhKacabPath { get; set; }
    }
}