// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsAgent
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public string BankId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public int IdentityTypeId { get; set; }
        public string IdentityNumber { get; set; }
        public bool IsActive { get; set; }
        public string AgentTypeId { get; set; }
        public string Status { get; set; }
        public string ApproveBy { get; set; }
        public DateTime? ApproveDate { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeIdAgentCoordinator { get; set; }
        public bool IsNpwp { get; set; }
        public string NpwpTypeId { get; set; }
        public string NpwpNumber { get; set; }
        public string NpwpName { get; set; }
        public string NpwpAddress { get; set; }
        public decimal? PkpCumulative { get; set; }
        public string IncentiveAgentTypeId { get; set; }
        public string AgentIdParent { get; set; }
        public string PositionIdAgentReference { get; set; }
        public bool IsFreeTextReference { get; set; }
        public string ReferenceNik { get; set; }
        public string ReferenceName { get; set; }
        public string ProfessionId { get; set; }
    }
}