// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsApupptRedZone
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID zona merah APUPPT
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// nama provinsi
        /// </summary>
        public string ProvinceName { get; set; }
        /// <summary>
        /// nama kabupaten
        /// </summary>
        public string RegencyName { get; set; }
        /// <summary>
        /// indikator untuk menandai kabupaten atau tidak
        /// </summary>
        public bool? FlagRegency { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool IsActive { get; set; }
    }
}