// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsApprovalUser
    {
        public MsApprovalUser()
        {
            MsApprovalMappingBm = new HashSet<MsApprovalMappingBm>();
        }

        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID skema approval
        /// </summary>
        public string ApprovalSchemeId { get; set; }
        /// <summary>
        /// ID tingkat approval
        /// </summary>
        public string ApprovalLevelId { get; set; }
        /// <summary>
        /// nomor induk karyawan
        /// </summary>
        public string Nik { get; set; }
        /// <summary>
        /// nama user/karyawan
        /// </summary>
        public string Nama { get; set; }
        /// <summary>
        /// ID jabatan
        /// </summary>
        public string JabatanId { get; set; }
        /// <summary>
        /// nama jabatan
        /// </summary>
        public string NamaJabatan { get; set; }
        /// <summary>
        /// indikator mandatory atau tidak
        /// </summary>
        public bool IsMandatory { get; set; }
        /// <summary>
        /// deskripsi kebijakan/aturan
        /// </summary>
        public string PolicyDesc { get; set; }

        public virtual MsApprovalLevel Approval { get; set; }
        public virtual ICollection<MsApprovalMappingBm> MsApprovalMappingBm { get; set; }
    }
}