// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsBiayaProsesHdr
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID biaya proses
        /// </summary>
        public string BiayaProsesId { get; set; }
        /// <summary>
        /// urutan biaya proses
        /// </summary>
        public int BiayaProsesSeq { get; set; }
        /// <summary>
        /// jangka waktu kredit (bulan)
        /// </summary>
        public int Tenor { get; set; }
        /// <summary>
        /// harga OTR minimum
        /// </summary>
        public decimal OtrMin { get; set; }
        /// <summary>
        /// harga OTR maksimum
        /// </summary>
        public decimal OtrMax { get; set; }
        /// <summary>
        /// jumlah nominal biaya proses
        /// </summary>
        public decimal? BiayaProses { get; set; }
        /// <summary>
        /// tipe cover asuransi
        /// </summary>
        public int InsCoverType { get; set; }
        /// <summary>
        /// jenis all risk (menentukan biaya proses)
        /// </summary>
        public int AllRisk { get; set; }
        /// <summary>
        /// jenis TLO (menentukan biaya proses)
        /// </summary>
        public int Tlo { get; set; }
        /// <summary>
        /// nominal Add-On
        /// </summary>
        public decimal AddOns1Nominal { get; set; }
        /// <summary>
        /// persentase Add-On
        /// </summary>
        public decimal? AddOns2Percentage { get; set; }
        /// <summary>
        /// tanggal mulai
        /// </summary>
        public DateTime StartDate { get; set; }
        /// <summary>
        /// tanggal selesai
        /// </summary>
        public DateTime EndDate { get; set; }
    }
}