// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsBiayaProsesDesc
    {
        /// <summary>
        /// ID biaya proses
        /// </summary>
        public string BiayaProsesId { get; set; }
        /// <summary>
        /// deskripsi biaya proses
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// deskripsi 2 biaya proses
        /// </summary>
        public string Description2 { get; set; }
        /// <summary>
        /// deskripsi 3 biaya proses
        /// </summary>
        public string Description3 { get; set; }
    }
}