// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsBranchCreditSource
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID sumber CAS cabang
        /// </summary>
        public int BranchCreditSourceId { get; set; }
        /// <summary>
        /// ID sumber CAS
        /// </summary>
        public string CreditSourceId { get; set; }
        /// <summary>
        /// ID cabang
        /// </summary>
        public int BranchId { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool? IsActive { get; set; }
        /// <summary>
        /// indikator foto aktif atau tidak
        /// </summary>
        public bool? IsActivePhoto { get; set; }
        /// <summary>
        /// indikator print survey report atau tidak
        /// </summary>
        public int? IsPrintSurveyReport { get; set; }
    }
}