// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsBrandItemType
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID tipe merk item
        /// </summary>
        public string ItemMerkTypeId { get; set; }
        /// <summary>
        /// ID merk item
        /// </summary>
        public string ItemMerkId { get; set; }
        /// <summary>
        /// ID item
        /// </summary>
        public string ItemId { get; set; }
        /// <summary>
        /// nama tipe item
        /// </summary>
        public string ItemTypeName { get; set; }
        /// <summary>
        /// harga OTR (on the road) atau keseluruhan
        /// </summary>
        public decimal? PriceOtr { get; set; }
        /// <summary>
        /// nominal buffer insentif
        /// </summary>
        public decimal? BufferInsentif { get; set; }
        /// <summary>
        /// nominal persen insentif
        /// </summary>
        public short? PersenInsentif { get; set; }
        /// <summary>
        /// ID grup tipe item
        /// </summary>
        public string ItemTypeGroupId { get; set; }
        /// <summary>
        /// ID tipe merk item baru
        /// </summary>
        public string ItemMerkTypeIdNew { get; set; }
        /// <summary>
        /// tanggal awal produksi
        /// </summary>
        public DateTime? ProductionStartDate { get; set; }
        /// <summary>
        /// tanggal akhir produksi
        /// </summary>
        public DateTime? ProductionEndDate { get; set; }
        /// <summary>
        /// ID model
        /// </summary>
        public string ModelId { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool IsActive { get; set; }
    }
}