// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsCasRoProgramAmount
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kategori repeat order
        /// </summary>
        public string RoCategoryId { get; set; }
        /// <summary>
        /// ID item
        /// </summary>
        public string ItemId { get; set; }
        /// <summary>
        /// jumlah nominal program
        /// </summary>
        public decimal AmountProgram { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public string IsActive { get; set; }
    }
}