// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsCmCutMaxDisbursement
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID status STNK
        /// </summary>
        public string StnkStatusId { get; set; }
        /// <summary>
        /// ID skema
        /// </summary>
        public string SchemeId { get; set; }
        /// <summary>
        /// ID kelas jenis aset
        /// </summary>
        public string AssetKindClassId { get; set; }
        /// <summary>
        /// nominal
        /// </summary>
        public decimal Value { get; set; }
    }
}