// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsDealerPersonel
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string DealerCode { get; set; }
        public int PersonelId { get; set; }
        public string PersonelName { get; set; }
        public int? JobTitleId { get; set; }
        public string Adddress { get; set; }
        public int LocationId { get; set; }
        public string BirthPlace { get; set; }
        public DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string HandphoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string PersonnelStatus { get; set; }
        public int? BankRefId { get; set; }
        public string Npwp { get; set; }
        public string NpwpName { get; set; }
        public string NpwpAddress { get; set; }
        public string NpwpType { get; set; }
        public DateTime? DeactivationDate { get; set; }
        public DateTime? ActivationDate { get; set; }
        public decimal RateRefundPersonal { get; set; }
        public decimal? PkpKumulatif { get; set; }
        public int? IsNpwp { get; set; }
    }
}