// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsDistrict
    {
        public MsDistrict()
        {
            MsVillage = new HashSet<MsVillage>();
        }

        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kecamatan
        /// </summary>
        public int DistrictId { get; set; }
        /// <summary>
        /// nama kecamatan
        /// </summary>
        public string DistrictName { get; set; }
        /// <summary>
        /// ID kabupaten
        /// </summary>
        public int RegencyId { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool? IsActive { get; set; }

        public virtual MsRegency Regency { get; set; }
        public virtual ICollection<MsVillage> MsVillage { get; set; }
    }
}