// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsEmployeeSync
    {
        /// <summary>
        /// nomor induk karyawan
        /// </summary>
        public string NoPeg { get; set; }
        /// <summary>
        /// nama karyawan
        /// </summary>
        public string Nama { get; set; }
        /// <summary>
        /// jenis kelamin karyawan
        /// </summary>
        public string Sex { get; set; }
        /// <summary>
        /// kode perusahaan
        /// </summary>
        public string KdPerusahaan { get; set; }
        /// <summary>
        /// nomor rekening karyawan
        /// </summary>
        public string NoRekening { get; set; }
        /// <summary>
        /// nama rekening karyawan
        /// </summary>
        public string NamaRekening { get; set; }
        /// <summary>
        /// kode bank
        /// </summary>
        public string KdBank { get; set; }
        /// <summary>
        /// nama bank
        /// </summary>
        public string NmBank { get; set; }
        /// <summary>
        /// alamat karyawan
        /// </summary>
        public string Alamat { get; set; }
        /// <summary>
        /// kota
        /// </summary>
        public string Kota { get; set; }
        /// <summary>
        /// alamat KTP karyawan
        /// </summary>
        public string AlamatId { get; set; }
        /// <summary>
        /// kota KTP
        /// </summary>
        public string KotaId { get; set; }
        /// <summary>
        /// nomor telepon karyawan
        /// </summary>
        public string Telp { get; set; }
        /// <summary>
        /// nomor handphone karyawan
        /// </summary>
        public string NoHp { get; set; }
        /// <summary>
        /// email karyawan
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// indikator sudah resign/keluar atau belum
        /// </summary>
        public byte? Fkeluar { get; set; }
        /// <summary>
        /// nomor KTP karyawan
        /// </summary>
        public string NoKtp { get; set; }
        /// <summary>
        /// nomor SIM karyawan
        /// </summary>
        public string NoSim { get; set; }
        /// <summary>
        /// nomor paspor karyawan
        /// </summary>
        public string NoPassport { get; set; }
        /// <summary>
        /// kode cabang
        /// </summary>
        public string KdCabang { get; set; }
        /// <summary>
        /// kode jabatan
        /// </summary>
        public string KdJabat { get; set; }
        /// <summary>
        /// nama jabatan karyawan
        /// </summary>
        public string NmJabat { get; set; }
        /// <summary>
        /// tanggal keluar karyawan
        /// </summary>
        public DateTime? TglKeluar { get; set; }
        /// <summary>
        /// tanggal masuk karyawan
        /// </summary>
        public DateTime? Tglmasuk { get; set; }
        /// <summary>
        /// status pegawai
        /// </summary>
        public byte? Stpegawai { get; set; }
        /// <summary>
        /// tanggal selesai kontrak
        /// </summary>
        public DateTime? Tglendkontrak { get; set; }
        /// <summary>
        /// kontrak ke
        /// </summary>
        public int? Kontrakke { get; set; }
        /// <summary>
        /// tanggal group
        /// </summary>
        public DateTime? Tglgroup { get; set; }
    }
}