// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsGeneralParameter
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// nama parameter
        /// </summary>
        public string Parameter { get; set; }
        /// <summary>
        /// nilai dari parameter
        /// </summary>
        public string Value { get; set; }
        /// <summary>
        /// satuan
        /// </summary>
        public string Unit { get; set; }
        /// <summary>
        /// deskripsi
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// indikator dapat dilihat atau tidak
        /// </summary>
        public int IsVisible { get; set; }
        /// <summary>
        /// indikator dapat diupdate atau tidak
        /// </summary>
        public int IsUpdateable { get; set; }
    }
}