// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsInsuranceCostRateR2Ojk
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID regional
        /// </summary>
        public string RegionId { get; set; }
        /// <summary>
        /// lama angsuran
        /// </summary>
        public byte Tenor { get; set; }
        /// <summary>
        /// bunga asuransi tahun ke 1
        /// </summary>
        public decimal InsuranceRateYear1 { get; set; }
        /// <summary>
        /// bunga asuransi tahun ke 2
        /// </summary>
        public decimal InsuranceRateYear2 { get; set; }
        /// <summary>
        /// bunga asuransi tahun ke 3
        /// </summary>
        public decimal InsuranceRateYear3 { get; set; }
        /// <summary>
        /// bunga asuransi tahun ke 4
        /// </summary>
        public decimal InsuranceRateYear4 { get; set; }
        /// <summary>
        /// bunga asuransi tahun ke 5
        /// </summary>
        public decimal InsuranceRateYear5 { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool IsActive { get; set; }
    }
}