// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsProductMarketing
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID produk marketing
        /// </summary>
        public string ProductMarketingId { get; set; }
        /// <summary>
        /// nama produk marketing
        /// </summary>
        public string ProductMarketingName { get; set; }
        /// <summary>
        /// ID perusahaan
        /// </summary>
        public int CompanyId { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool IsActive { get; set; }
        /// <summary>
        /// ID produk marketing lama
        /// </summary>
        public string ProductMarketingIdOld { get; set; }
    }
}