// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsPtInsurance
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID asuransi
        /// </summary>
        public string InsuranceId { get; set; }
        /// <summary>
        /// nama asuransi
        /// </summary>
        public string InsuranceName { get; set; }
        /// <summary>
        /// asuransi awal
        /// </summary>
        public string InsuranceInitial { get; set; }
        /// <summary>
        /// orang yang dapat dihubungi
        /// </summary>
        public string ContactPerson { get; set; }
        /// <summary>
        /// alamat
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// kota
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// nomor telepon
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// nomor fax
        /// </summary>
        public string FaxNumber { get; set; }
        /// <summary>
        /// ID bank
        /// </summary>
        public string BankId { get; set; }
        /// <summary>
        /// nomor rekening
        /// </summary>
        public string AccountNumber { get; set; }
        /// <summary>
        /// nama rekening
        /// </summary>
        public string AccountName { get; set; }
        /// <summary>
        /// email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public int? IsActive { get; set; }
    }
}