// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsRiskCategory
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kategori resiko
        /// </summary>
        public int RiskCategoryId { get; set; }
        /// <summary>
        /// deskripsi dari kategori resiko
        /// </summary>
        public string RiskCategoryDescription { get; set; }
        /// <summary>
        /// poin
        /// </summary>
        public decimal? Point { get; set; }
        /// <summary>
        /// rentang awal
        /// </summary>
        public int? StartRange { get; set; }
        /// <summary>
        /// rentang akhir
        /// </summary>
        public int? EndRange { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool? IsActive { get; set; }
    }
}