// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsServiceBureauHeader
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID biro jasa
        /// </summary>
        public string ServiceBureauId { get; set; }
        /// <summary>
        /// tipe biro jasa
        /// </summary>
        public string ServiceBureauType { get; set; }
        /// <summary>
        /// nama biro jasa
        /// </summary>
        public string ServiceBureauName { get; set; }
        /// <summary>
        /// nomor lisensi bisnis
        /// </summary>
        public string BusinessLicenseNumber { get; set; }
        /// <summary>
        /// alamat biro jasa
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// kota biro jasa
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// kode pos biro jasa
        /// </summary>
        public string ZipCode { get; set; }
        /// <summary>
        /// nomor telepon biro jasa
        /// </summary>
        public string TelephoneNumber { get; set; }
        /// <summary>
        /// nomor fax biro jasa
        /// </summary>
        public string FaxNumber { get; set; }
        /// <summary>
        /// email biro jasa
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// nomor akta
        /// </summary>
        public string AktaNo { get; set; }
        /// <summary>
        /// nomor KTP
        /// </summary>
        public string KtpNo { get; set; }
        /// <summary>
        /// nomor NPWP
        /// </summary>
        public string NpwpNo { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public int? IsActive { get; set; }
    }
}