// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsYearFrame
    {
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// kode rangka
        /// </summary>
        public string ChasisCode { get; set; }
        /// <summary>
        /// tahun kendaraan
        /// </summary>
        public string VehicleYear { get; set; }
        /// <summary>
        /// indikator aktif atau tidaknya master data
        /// </summary>
        public bool IsActive { get; set; }
    }
}