// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_agent_ms_detail_by_idResult
    {
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string BranchID { get; set; }
        public string BankID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string HP { get; set; }
        public int? IdentitasID { get; set; }
        public string NoIdentitas { get; set; }
        public bool? IsActive { get; set; }
        public string TipePerantara { get; set; }
        public string Status { get; set; }
        public string AgentKoor { get; set; }
        public string TipeNPWP { get; set; }
        public string NoNPWP { get; set; }
        public string NamaNPWP { get; set; }
        public string AlamatNPWP { get; set; }
        public string InsentifID { get; set; }
        public string Pekerjaan { get; set; }
        public string NPPLama { get; set; }
        public string NoRek { get; set; }
        [Column("Nama Rek")]
        public string NamaRek { get; set; }
        [Column("Luas Area RT")]
        public string LuasAreaRT { get; set; }
        [Column("Jumlah KK di RT Tersebut")]
        public string JumlahKKdiRTTersebut { get; set; }
        [Column("Jumlah Usia Produktif")]
        public string JumlahUsiaProduktif { get; set; }
        [Column("Jumlah Anak")]
        public string JumlahAnak { get; set; }
        [Column("Jenis Usaha Warga")]
        public string JenisUsahaWarga { get; set; }
        public string PNS { get; set; }
        [Column("Karyawan Swasta")]
        public string KaryawanSwasta { get; set; }
        public string Wiraswasta { get; set; }
        public string Lainnya { get; set; }
        public string Jumlah { get; set; }
        public string doc_perjanjian_kerja_sama_name { get; set; }
        public string doc_surat_rekomendasi_kacab_name { get; set; }
        public string doc_ktp_name { get; set; }
        public string doc_buku_tabungan_name { get; set; }
        public string doc_npwp_name { get; set; }
        public string doc_foto_bersama_mh_kacab_name { get; set; }
    }
}
