// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_pagination_lookup_bankResult
    {
        public long? RowNumber { get; set; }
        [Column("Bank No")]
        public string BankNo { get; set; }
        [Column("Bank Name")]
        public string BankName { get; set; }
        [Column("Account No")]
        public string AccountNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        [Column("Branch ID")]
        public string BranchID { get; set; }
    }
}
