// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_pagination_lookup_agentResult
    {
        public long? RowNumber { get; set; }
        [Column("Employee ID")]
        public string EmployeeID { get; set; }
        [Column("Employee Name")]
        public string EmployeeName { get; set; }
        [Column("First Name")]
        public string FirstName { get; set; }
        [Column("Last Name")]
        public string LastName { get; set; }
        [Column("Position Name")]
        public string PositionName { get; set; }
        public string PT { get; set; }
        [Column("Branch ID")]
        public string BranchID { get; set; }
        public string Address { get; set; }
    }
}
