// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_pagination_BPKBReceiverResult
    {
        public long? RowNumber { get; set; }
        public string receiver_code { get; set; }
        public string receiver_name { get; set; }
    }
}
