// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_company_branch_listResult
    {
        public int company_id { get; set; }
        public string branch_id { get; set; }
        public string area_id { get; set; }
        public string parent_branch_id { get; set; }
        public bool is_head_office { get; set; }
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public string branch_province { get; set; }
        public bool? is_active { get; set; }
        public string branch_partner_id { get; set; }
    }
}
