// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class sp_get_ownership_proofResult
    {
        public int ownership_proof_id { get; set; }
        public string ownership_proof_desc { get; set; }
    }
}
