// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FINCORE.LIBRARY.DTO.EntityFramework.Termination.TerminationModel;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Termination.TerminationContext
{
    public partial class TerminationContext : DbContext
    {
        public TerminationContext()
        {
        }

        public TerminationContext(DbContextOptions<TerminationContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Newpo> Newpos { get; set; }
        public virtual DbSet<Newpo1> Newpo1s { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Newpo>(entity =>
            {
                entity.HasKey(e => e.PoNo)
                    .HasName("PK__NEWPO__A4C0162D742F6C5D");

                entity.ToTable("NEWPO");

                entity.Property(e => e.PoNo)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Alamat)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatKtp)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("AlamatKTP");

                entity.Property(e => e.AlamatPasangan)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatPenjamin)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatPerusahaanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AngsuranAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.AsalKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BerlakuHingga).HasColumnType("date");

                entity.Property(e => e.BiayaAdministrasiAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BiayaAdministrasiDealerAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BiayaAsuransiAsset).HasColumnType("numeric(10, 0)");

                entity.Property(e => e.BiayaKesehatan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BiayaPendidikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BiayaPengeluaranRt)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("BiayaPengeluaranRT");

                entity.Property(e => e.BiayaProvisiAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BidangUsahaCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BidangUsahaTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BuktiKepemilikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CicilanLain)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataPriceAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.DealerAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DepositAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EmailPerusahaanCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ExistingCustomerRo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ExistingCustomerRO");

                entity.Property(e => e.FakturBpkbAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.GolDebitur)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Handphone)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.HargaOtrasset)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("HargaOTRAsset");

                entity.Property(e => e.HubunganReferensiPemohon)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsAdaPenjamin)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.IsAdaReferensi)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.IsAvalisAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsKtpseumurHidup)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("IsKTPSeumurHidup");

                entity.Property(e => e.IsPergiLn)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("IsPergiLN");

                entity.Property(e => e.IsSurvey)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IssueDate).HasColumnType("date");

                entity.Property(e => e.ItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JabatanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JarakKantorKeKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JeniNarasumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JenisKelamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JenisKomoditiTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JumlahBiayaCicilan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.JumlahKaryawan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JumlahPencairanAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.JumlahTanggungan)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Kabupaten)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Kecamatan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Kelurahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KetPenghasilanTambahanPasangan)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Kewarganegaraan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodeCabang)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePos)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosLokasiPasangan)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosTambahan)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.KondisiAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KondisiRumah)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Ktp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTP");

                entity.Property(e => e.Ktpdireksi)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTPDireksi");

                entity.Property(e => e.Ktpkomisaris)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTPKomisaris");

                entity.Property(e => e.LamaAngsuranAsset)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.LamaBekerjaTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LamaUsahaCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Lokasi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LokasiKtp)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("LokasiKTP");

                entity.Property(e => e.MarketPriceAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.MarketingHeadAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MerkItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ModelItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaBuktiKepemilikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaDirektur)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaIbuKandung)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaKomisaris)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaLengkapReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNarasumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNasabah)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNotarisAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNotarisPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPerusahaanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaStnkAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoAktaPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoFaxCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoHpReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoIdentitas)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoNpwp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoNPWP");

                entity.Property(e => e.NoNpwppt)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoNPWPPT");

                entity.Property(e => e.NoSiup)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoSIUP");

                entity.Property(e => e.NoTdp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoTDP");

                entity.Property(e => e.NoTeleponPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.OrangTua)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PekerjaanPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PekerjaanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PembayaranKonsumenAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PenghasilanPasangan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanTambahan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanTambahanPasangan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanUtama).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Penilaian)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProdukAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Profesi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Provinsi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Situ)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("SITU");

                entity.Property(e => e.SitusCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusPernikahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusTempatTinggal)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SurveyorAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TahunKendaraanAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TanggalLahir).HasColumnType("date");

                entity.Property(e => e.TanggalLahirPasangan).HasColumnType("date");

                entity.Property(e => e.TanggalLahirPenjamin).HasColumnType("date");

                entity.Property(e => e.Telepon)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TeleponPerusahaanTambahan)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahirPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahirPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglAktaPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglJatuhTempoSitu)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoSITU");

                entity.Property(e => e.TglJatuhTempoSiup)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoSIUP");

                entity.Property(e => e.TglJatuhTempoTdp)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoTDP");

                entity.Property(e => e.TglTerbitSitu)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitSITU");

                entity.Property(e => e.TglTerbitSiup)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitSIUP");

                entity.Property(e => e.TglTerbitTdp)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitTDP");

                entity.Property(e => e.TipeAplikasiAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeFinanceAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeIdentitas)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeIdentitasPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipePerantaraAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UangMukaAsset).HasColumnType("numeric(18, 0)");
            });

            modelBuilder.Entity<Newpo1>(entity =>
            {
                entity.HasKey(e => e.PoNo)
                    .HasName("PK__NEWPO1__A4C0162DC4182650");

                entity.ToTable("NEWPO1");

                entity.Property(e => e.PoNo)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Alamat)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatKtp)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("AlamatKTP");

                entity.Property(e => e.AlamatPasangan)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatPenjamin)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatPerusahaanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AlamatReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AngsuranAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.AsalKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BerlakuHingga).HasColumnType("date");

                entity.Property(e => e.BiayaAdministrasiAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BiayaAdministrasiDealerAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BiayaAsuransiAsset).HasColumnType("numeric(10, 0)");

                entity.Property(e => e.BiayaKesehatan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BiayaPendidikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BiayaPengeluaranRt)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("BiayaPengeluaranRT");

                entity.Property(e => e.BiayaProvisiAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.BidangUsahaCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BidangUsahaTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BuktiKepemilikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CicilanLain)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataPriceAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.DealerAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DepositAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EmailPerusahaanCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ExistingCustomerRo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ExistingCustomerRO");

                entity.Property(e => e.FakturBpkbAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.GolDebitur)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Handphone)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.HargaOtrasset)
                    .HasColumnType("numeric(18, 0)")
                    .HasColumnName("HargaOTRAsset");

                entity.Property(e => e.HubunganReferensiPemohon)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsAdaPenjamin)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.IsAdaReferensi)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.IsAvalisAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsKtpseumurHidup)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("IsKTPSeumurHidup");

                entity.Property(e => e.IsPergiLn)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("IsPergiLN");

                entity.Property(e => e.IsSurvey)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IssueDate).HasColumnType("date");

                entity.Property(e => e.ItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JabatanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JarakKantorKeKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JeniNarasumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JenisKelamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JenisKomoditiTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JumlahBiayaCicilan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.JumlahKaryawan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.JumlahPencairanAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.JumlahTanggungan)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Kabupaten)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KabupatenTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Kecamatan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KecamatanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Kelurahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KelurahanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KetPenghasilanTambahanPasangan)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Kewarganegaraan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodeCabang)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePos)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosLokasiPasangan)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KodePosTambahan)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.KondisiAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.KondisiRumah)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Ktp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTP");

                entity.Property(e => e.Ktpdireksi)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTPDireksi");

                entity.Property(e => e.Ktpkomisaris)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("KTPKomisaris");

                entity.Property(e => e.LamaAngsuranAsset)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.LamaBekerjaTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LamaUsahaCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Lokasi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.LokasiKtp)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("LokasiKTP");

                entity.Property(e => e.MarketPriceAsset).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.MarketingHeadAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.MerkItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ModelItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaBuktiKepemilikan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaDirektur)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaIbuKandung)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaKomisaris)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaLengkapReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNarasumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNasabah)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNotarisAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaNotarisPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaPerusahaanTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NamaStnkAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoAktaPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoFaxCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoHpReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoIdentitas)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoNpwp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoNPWP");

                entity.Property(e => e.NoNpwppt)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoNPWPPT");

                entity.Property(e => e.NoSiup)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoSIUP");

                entity.Property(e => e.NoTdp)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("NoTDP");

                entity.Property(e => e.NoTeleponPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.NoTelpReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.OrangTua)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PekerjaanPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PekerjaanPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PembayaranKonsumenAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PenghasilanPasangan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanTambahan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanTambahanPasangan).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.PenghasilanUtama).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Penilaian)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProdukAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Profesi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Provinsi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiLokasiPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiReferensi)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ProvinsiTambahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Situ)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("SITU");

                entity.Property(e => e.SitusCorporate)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusPernikahan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StatusTempatTinggal)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.SurveyorAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TahunKendaraanAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TanggalLahir).HasColumnType("date");

                entity.Property(e => e.TanggalLahirPasangan).HasColumnType("date");

                entity.Property(e => e.TanggalLahirPenjamin).HasColumnType("date");

                entity.Property(e => e.Telepon)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TeleponPerusahaanTambahan)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahirPasangan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TempatLahirPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglAktaPendirianPerusahaan)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglAktaPengurusAkhir)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TglJatuhTempoSitu)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoSITU");

                entity.Property(e => e.TglJatuhTempoSiup)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoSIUP");

                entity.Property(e => e.TglJatuhTempoTdp)
                    .HasColumnType("date")
                    .HasColumnName("TglJatuhTempoTDP");

                entity.Property(e => e.TglTerbitSitu)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitSITU");

                entity.Property(e => e.TglTerbitSiup)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitSIUP");

                entity.Property(e => e.TglTerbitTdp)
                    .HasColumnType("date")
                    .HasColumnName("TglTerbitTDP");

                entity.Property(e => e.TipeAplikasiAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeFinanceAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeIdentitas)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeIdentitasPenjamin)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeItemAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipeKonsumen)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TipePerantaraAsset)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.UangMukaAsset).HasColumnType("numeric(18, 0)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}