// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class Arcard
    {
        public string BranchId { get; set; }
        public string CreditId { get; set; }
        public int Period { get; set; }
        public int PeriodSecq { get; set; }
        public decimal ArcardId { get; set; }
        public DateTime CollectionDate { get; set; }
        public decimal FirstInstallment { get; set; }
        public decimal Installment { get; set; }
        public decimal Principal { get; set; }
        public decimal Interest { get; set; }
        public decimal OstAr { get; set; }
        public decimal OstOp { get; set; }
        public decimal OstUli { get; set; }
        public decimal? CollectionId { get; set; }
        public DateTime? PayDate { get; set; }
        public decimal? PayAmt { get; set; }
        public string UsrCrt { get; set; }
        public DateTime DtmCrt { get; set; }
        public string UsrUpd { get; set; }
        public DateTime? DtmUpd { get; set; }
        public string IsAr { get; set; }
        public string ArvoucherNo { get; set; }
        public DateTime? ArpayDate { get; set; }
    }
}