// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class CfverifikasiKonsumenAplikasiIn
    {
        public string Cmno { get; set; }
        public int IdbindField { get; set; }
        public bool IsTrue { get; set; }
        public string FileNameAplikasiIn { get; set; }
        public string FilePathAplikasiIn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
    }
}