// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class fnEPKonversiUppingOTRResult
    {
        public decimal? AssetCost { get; set; }
        public decimal? AdminFee { get; set; }
        public decimal? InsuranceFee { get; set; }
        public decimal? UangMuka { get; set; }
        public decimal? UangMukaMurni { get; set; }
        public decimal? JmlPembiayaan { get; set; }
        public decimal? Bunga { get; set; }
        public decimal? EffRate { get; set; }
        public decimal? FlatRate { get; set; }
        public decimal? TotalUpping { get; set; }
        public int? CountUpping { get; set; }
        public decimal? Disc_Deposit { get; set; }
        public decimal? AdminFeeMin { get; set; }
        public decimal? PersenDPCF { get; set; }
        public decimal? BiayaLainUppingOTR { get; set; }
        public decimal? BiayaProvisi { get; set; }
        public decimal? AmountPH { get; set; }
    }
}
