// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class fnGenerateAmortizationResult
    {
        public string CreditId { get; set; }
        public int Period { get; set; }
        public bool FloatingMark { get; set; }
        public decimal PeriodicInterestRate { get; set; }
        public DateTime DueDate { get; set; }
        public decimal InstallmentAmount { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal PrincipalRecovery { get; set; }
        public decimal OSPrincipalAmount { get; set; }
        public decimal OSInterestAmount { get; set; }
        public decimal OSInstallmentAmount { get; set; }
        public string ErrorMessage { get; set; }
    }
}
