// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class NeoScoreLog
    {
        public string Id { get; set; }
        public string CreditId { get; set; }
        public string UserId { get; set; }
        public string Method { get; set; }
        public string Menu { get; set; }
        public string MenuDetail { get; set; }
        public string Parameter { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }
        public DateTime? LogDate { get; set; }
        public int? TotalScore { get; set; }
    }
}