// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_approve_nppResult
    {
        public string CreditId { get; set; }
        public string CompanyId { get; set; }
        public DateTime? AgreementDate { get; set; }
        public string ChasisNo { get; set; }
        public string MachineNo { get; set; }
        public string CarPlateNo { get; set; }
        public string ItemTypeName { get; set; }
        public string YearItem { get; set; }
        public string ItemMerk { get; set; }
        public string ItemId { get; set; }
    }
}
