// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_check_data_referensi_slikResult
    {
        public string NIK { get; set; }
        public string FCLID { get; set; }
        public string NamaBank { get; set; }
        public string JenisFasilitas { get; set; }
        public decimal Plafon { get; set; }
        public decimal OS { get; set; }
        public byte StatusKol { get; set; }
        public byte? MaxKol { get; set; }
        public string Status { get; set; }
    }
}
