// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_price_awalResult
    {
        public string CreditId { get; set; }
        public byte? Tenor { get; set; }
        public decimal? TotalUppingOtr { get; set; }
        public decimal? NettDownPayment { get; set; }
        public decimal? AdminFee { get; set; }
        public decimal? InsuranceFee { get; set; }
        public decimal? BiayaProvisiIns { get; set; }
        public decimal? UangMuka { get; set; }
        public decimal? JmlPembiayaan { get; set; }
        public decimal? AmountInstallment { get; set; }
        public decimal? RateValue { get; set; }
        public decimal? FlatRate { get; set; }
        public decimal? dealer_admin_fee { get; set; }
        public decimal? PersenNfa { get; set; }
    }
}
