// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_history_approvalResult
    {
        public string No { get; set; }
        public string NIK { get; set; }
        public string Nama { get; set; }
        public string Keputusan { get; set; }
        public string Tanggal { get; set; }
        public string Alasan { get; set; }
    }
}
