// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_process_provisi_insResult
    {
        public string nominal_biaya_proses { get; set; }
        public string biaya_provisi_ins { get; set; }
        public string biaya_proses { get; set; }
        public string biaya_asuransi_kerugian { get; set; }
    }
}
