// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_fotocek_caResult
    {
        public string Photo_Type_ID { get; set; }
        public string Photo_ID { get; set; }
        public string Photo_Desc { get; set; }
        public string file_name { get; set; }
        public string urlfoto { get; set; }
    }
}
