// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_check_user_print_poResult
    {
        public string position_id { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
    }
}
