// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_approval_schemeResult
    {
        public string ApprovalSchemeID { get; set; }
        public string ApprovalSchemeDesc { get; set; }
    }
}
