// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_employee_surcodeResult
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Alias { get; set; }
        public string IDNo { get; set; }
        public string IDAddress { get; set; }
        public string IDCity { get; set; }
        public string IDZipCode { get; set; }
        public int? IDLocationID { get; set; }
        public string NPWPNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public int? LocationID { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public int? Religion { get; set; }
        public string BloodType { get; set; }
        public string BirthPlace { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? JoinDateReal { get; set; }
        public DateTime? JoinDateTax { get; set; }
        public string Gender { get; set; }
        public string MarriedStatus { get; set; }
        public string Memo { get; set; }
        public bool? IsDPLK { get; set; }
        public string ParticipationNo { get; set; }
        public DateTime? ParticipationDate { get; set; }
        public byte? IsExpatriate { get; set; }
        public byte? IsSchedulingShift { get; set; }
        public string DefaultShift { get; set; }
        public string TaxStatus { get; set; }
        public int? CompanyID { get; set; }
        public int? CompanyBranchID { get; set; }
        public string OrgIDDir { get; set; }
        public string OrgIDDiv { get; set; }
        public string OrgIDDept { get; set; }
        public string OrgIDSubDept { get; set; }
        public string PositionID { get; set; }
        public int? PositionSecqID { get; set; }
        public string Grade { get; set; }
        public string RangeID { get; set; }
        public byte? JobStatus { get; set; }
        public byte? EmployeeStatus { get; set; }
        public DateTime? ContractPeriodStart { get; set; }
        public DateTime? ContractPeriodEnd { get; set; }
        public bool? IsCertified { get; set; }
        public string CertifiedNo { get; set; }
        public DateTime? CertifiedDate { get; set; }
        public string CertifiedRemarks { get; set; }
        public byte? PaymentType { get; set; }
        public string BankID { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdateBy { get; set; }
        public DateTime? LastUpdateOn { get; set; }
        public int? SpvCompanyID_ { get; set; }
        public int? SpvCompanyBranchID_ { get; set; }
        public string SpvPositionID_ { get; set; }
        public int? SpvPositionSecqID_ { get; set; }
        public bool IsActive { get; set; }
        public byte? EmployeeStatus2 { get; set; }
    }
}
