// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_life_insurance_kreditResult
    {
        public string mega_insurance_fee_kredit { get; set; }
        public string handphone_fee_kredit { get; set; }
    }
}
