// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_pagination_lookup_CGSNoResult
    {
        public long? RowNumber { get; set; }
        public string CGSCabangNo { get; set; }
        public string NoMemo { get; set; }
        public string NamaMemo { get; set; }
        public string BroadCastDate { get; set; }
    }
}
