// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_ms_product_marketingResult
    {
        public string product_marketing_id { get; set; }
        public string product_marketing_name { get; set; }
        public string company_id { get; set; }
    }
}
