// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_analisa_cmo_caResult
    {
        public string CASId { get; set; }
        public string Capacity { get; set; }
        public string Capital { get; set; }
        public string Character { get; set; }
        public string Condition { get; set; }
        public string Collateral { get; set; }
        public string Strenght { get; set; }
        public string Weakness { get; set; }
        public string created_by { get; set; }
        public DateTime? created_on { get; set; }
        public string last_update_by { get; set; }
        public DateTime? last_update_on { get; set; }
    }
}
