// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_cmo_dealer_caResult
    {
        public string credit_id { get; set; }
        public string NIK_surveryor_code { get; set; }
        public string employeename { get; set; }
        public string dealer_code { get; set; }
        public string dealer_name { get; set; }
    }
}
