// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_pagination_lookup_perantaraResult
    {
        public long? RowNumber { get; set; }
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string BranchID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
    }
}
