// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_BPKB_BAST_IN_DtlResult
    {
        public string BpkbNo { get; set; }
        public string BrandName { get; set; }
        public string ItemColor { get; set; }
        public string ChasisNo { get; set; }
        public string MachineNo { get; set; }
        public string QQName { get; set; }
        public string CustomerName { get; set; }
    }
}
