// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_DocumentFieldResult
    {
        public int IDBind { get; set; }
        public string Fieldname { get; set; }
        public bool is_active { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
    }
}
