// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_pagination_BPKBDealerResult
    {
        public long? RowNumber { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ItemMerk { get; set; }
        public string ItemMerkID { get; set; }
    }
}
