// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_data_VerifikasiKonsumenResult
    {
        public string Cmno { get; set; }
        public string credit_id { get; set; }
        public string VerifikasiNo { get; set; }
        public string AgreementNumber { get; set; }
        public string AlamatPelanggan { get; set; }
        public string NamaPelanggan { get; set; }
        public string Phone { get; set; }
        public string StatusVerifikasi { get; set; }
        public string NamaStnk { get; set; }
        public string NamaPasanganStnk { get; set; }
        public DateTime? TglTerimaTagihan { get; set; }
        public DateTime? TglKonfirmasi { get; set; }
        public string JamKonfirmasi { get; set; }
        public int? OptBisaDiHubungi { get; set; }
        public bool? option_item_received_date { get; set; }
        public DateTime? OptTglTerimaMotorSebenarnya { get; set; }
        public bool? option_item_type { get; set; }
        public string OptTipeMotorSebenarnya { get; set; }
        public bool? option_installment { get; set; }
        public decimal? OptAngsuranSebenarnya { get; set; }
        public bool? option_tenor { get; set; }
        public int? OptTenorSebenarnya { get; set; }
        public bool? option_consumen_payment { get; set; }
        public decimal? OptDpsetorSebenarnya { get; set; }
        public string NamaPenerimaMotor { get; set; }
        public string HubunganPenerimaMotor { get; set; }
        public string PermintaanJt { get; set; }
        public string CatatanLain { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime TglTerimaPinjaman { get; set; }
        public string Tipe { get; set; }
        public decimal? Installment { get; set; }
        public int? Tenor { get; set; }
        public decimal? DPSetor { get; set; }
        public int? OptBiayaAdmin { get; set; }
        public decimal? BiayaAdmin { get; set; }
    }
}
