// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_pagination_BPKBAsuransiResult
    {
        public long? RowNumber { get; set; }
        public string InsID { get; set; }
        public string InsName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
    }
}
