// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_ms_item_brand_typeResult
    {
        public string item_brand_type_id { get; set; }
        public string item_brand_id { get; set; }
        public string item_id { get; set; }
        public string item_type_name { get; set; }
        public string item_type_group_id { get; set; }
        public string item_merk_type_new_id { get; set; }
    }
}
