// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_approval_userResult
    {
        public string NIK { get; set; }
        public string nama { get; set; }
        public string jabatan_id { get; set; }
        public string nama_jabatan { get; set; }
    }
}
