// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_ngulikResult
    {
        public string KodeCabang { get; set; }
        public string PoNo { get; set; }
        public string TipeKonsumen { get; set; }
        public string ExistingCustomerRO { get; set; }
        public string NamaNasabah { get; set; }
    }
}
