// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_agreement_number_oldResult
    {
        public string lessee_id { get; set; }
        public string npp_no { get; set; }
        public string item_merk { get; set; }
        public string item_type_name { get; set; }
    }
}
