// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_ms_asset_kind_classResult
    {
        public string asset_kind_id { get; set; }
        public string asset_kind_class_id { get; set; }
        public string asset_kind_class_name { get; set; }
    }
}
