// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_dealer_by_codeResult
    {
        public string created_by { get; set; }
        public DateTime? created_on { get; set; }
        public string last_updated_by { get; set; }
        public DateTime? last_updated_on { get; set; }
        public string dealer_code { get; set; }
        public string dealer_name { get; set; }
        public bool is_authorized_dealer { get; set; }
        public bool is_selling_new_product_only { get; set; }
        public string product_asset_kind_id { get; set; }
        public string item_merk { get; set; }
        public string dealer_parent { get; set; }
        public string main_dealer_id { get; set; }
        public string dealer_group_id { get; set; }
        public int contact_person_job_title { get; set; }
        public string owner_name { get; set; }
        public string contact_person { get; set; }
        public string KTP_no { get; set; }
        public string KTP_name { get; set; }
        public string KTP_address { get; set; }
        public string address { get; set; }
        public string location_id { get; set; }
        public string telephone_number { get; set; }
        public string mobile_phone_number { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string MOU_no { get; set; }
        public DateTime? MOU_date { get; set; }
        public bool? is_bank_charges { get; set; }
        public bool? is_payment_before_due { get; set; }
        public string NPWP_no { get; set; }
        public string NPWP_name { get; set; }
        public string NPWP_address { get; set; }
        public string NPWP_type { get; set; }
        public bool? is_prepayment { get; set; }
        public decimal? prepayment { get; set; }
        public string notes { get; set; }
        public bool? is_used_car { get; set; }
        public string status_dealer { get; set; }
        public DateTime? activation_date { get; set; }
        public DateTime? deactivation_date { get; set; }
        public decimal rate_refund { get; set; }
        public decimal? PKP_cumulative { get; set; }
        public string status_rate_refund { get; set; }
        public string MP_master_dealer_file { get; set; }
        public string SIUP_file { get; set; }
        public string TDP_NIB_file { get; set; }
        public string NPWP_file { get; set; }
        public string KTP_owner_file { get; set; }
        public string SPT_account_book_file { get; set; }
        public bool? is_sync { get; set; }
        public string asset_brand_id { get; set; }
    }
}
