// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_get_tipe_perantaraResult
    {
        public string KdPerantara { get; set; }
        public string Nama_Perantara { get; set; }
        public string isReqKoor { get; set; }
    }
}
