// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_npp_name_change_receiptResult
    {
        public string ReceiptNo { get; set; }
        public string PayerName { get; set; }
        public string PaymentAmountInWord { get; set; }
        public string PaymentPurpose { get; set; }
        public string PaymentDateDayMonth { get; set; }
        public string PaymentDateYear { get; set; }
        public int PaymentAmount { get; set; }
        public string PaymentAmountFormatted { get; set; }
    }
}
