// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_npp_consument_statement_letterResult
    {
        public string CreditId { get; set; }
        public string AgreementDate { get; set; }
        public string CustomerName { get; set; }
        public string Occupation { get; set; }
        public string CustomerAdress { get; set; }
        public string LetterDateDayMonth { get; set; }
        public string LetterDateYear { get; set; }
        public string BranchName { get; set; }
    }
}
