// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_vertelResult
    {
        public string VerifikasiNo { get; set; }
        public string CMNo { get; set; }
        public string AgreementNumber { get; set; }
        public string NamaPelanggan { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string OptBisaDiHubungi { get; set; }
        public string NamaSTNK { get; set; }
        public string NamaPasanganSTNK { get; set; }
        public DateTime? TglTerimaTagihan { get; set; }
        public string TglKonfirmasi { get; set; }
        public string JamKonfirmasi { get; set; }
        public string TglApproveNPP { get; set; }
        public string TglTerimaMotor { get; set; }
        public string ItemTypeName { get; set; }
        public string Installment { get; set; }
        public string Tenor { get; set; }
        public string lblTglTerimaMotorYa { get; set; }
        public string lblTipeMotorYa { get; set; }
        public string lblAngsuranYa { get; set; }
        public string lblTenorYa { get; set; }
        public string OptTglTerimaMotorSebenarnya { get; set; }
        public string OptTipeMotorSebenarnya { get; set; }
        public string OptAngsuranSebenarnya { get; set; }
        public string OptTenorSebenarnya { get; set; }
        public string NamaPenerimaMotor { get; set; }
        public string HubunganPenerimaMotor { get; set; }
        public string PermintaanJT { get; set; }
        public string CatatanLain { get; set; }
        public decimal JumlahNominalAdmin { get; set; }
        public string AdminNPP { get; set; }
        public string NamaCA { get; set; }
        public string NamaKepalaCabang { get; set; }
    }
}
