// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_npp_approval_letterResult
    {
        public string CreditID { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceOccupation { get; set; }
        public string ReferenceIdentityNumber { get; set; }
        public string ReferenceAddress { get; set; }
        public string HomePhone { get; set; }
        public string MobileNumber { get; set; }
        public string OfficeNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerOccupation { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerIdentityNumber { get; set; }
        public string ApproveDate { get; set; }
        public string LetterDateDayMonth { get; set; }
        public string LetterDateYear { get; set; }
        public string BranchName { get; set; }
    }
}
