// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_CA_SLIKResult
    {
        public string PlafonCurrency { get; set; }
        public string OSCurrency { get; set; }
        public string bank_name { get; set; }
        public string created_by { get; set; }
        public DateTime? created_on { get; set; }
        public string last_updated_by { get; set; }
        public DateTime? last_updated_on { get; set; }
        public int id { get; set; }
        public string CA_no { get; set; }
        public string relation { get; set; }
        public string facility_name { get; set; }
        public string bank_id { get; set; }
        public string facility_type { get; set; }
        public string plafon { get; set; }
        public string OS { get; set; }
        public string KOL_status { get; set; }
        public string KOL_max { get; set; }
        public string status { get; set; }
    }
}
