// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_vertel_dokumen_inResult
    {
        public long? No { get; set; }
        public string DokuemnAplikasiIn { get; set; }
        public string Fisik { get; set; }
    }
}
