// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class sp_print_npp_second_statement_letterResult
    {
        public string CreditId { get; set; }
        public string CustomerName { get; set; }
        public string Occupation { get; set; }
        public string CustomerAddress { get; set; }
        public string IdentityNumber { get; set; }
        public string ApproveDate { get; set; }
        public string PurchasePrice { get; set; }
        public string DownPayment { get; set; }
        public string PrincipalFinancing { get; set; }
        public string InterestAmount { get; set; }
        public double InterestRate { get; set; }
        public string DebtAmount { get; set; }
        public string AdminFee { get; set; }
        public string ProvisionFee { get; set; }
        public string InsuranceFee { get; set; }
        public string SurveyFee { get; set; }
        public string LetterDateDayMonth { get; set; }
        public string LetterDateYear { get; set; }
        public string BranchName { get; set; }
    }
}
