// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class SP_RFNDO_Check_ByNppResult
    {
        public int err_id { get; set; }
        public string err_msg { get; set; }
    }
}
