// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class SP_RFNDO_GetAssetDetailResult
    {
        public string credit_id { get; set; }
        public string QQ_name { get; set; }
        public string identity_number { get; set; }
        public string itemtypename { get; set; }
        public decimal? asset_cost { get; set; }
        public string item_merk_id { get; set; }
        public string ItemMerkTypeID { get; set; }
        public string itemmerk { get; set; }
        public string bpkbno { get; set; }
        public string Car_NO { get; set; }
        public DateTime? invoice_date { get; set; }
        public string FakturNo { get; set; }
        public string Lokasi { get; set; }
        public string chasis_no { get; set; }
        public string machine_no { get; set; }
        public DateTime? bpkb_date { get; set; }
        public string status { get; set; }
        public string dokumen_pelengkap { get; set; }
    }
}
