// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class spGetListNewVertelLookUpPagingResult
    {
        public long? RowNumber { get; set; }
        public string CMNo { get; set; }
        public string BranchID { get; set; }
        public string NPPNo { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Item { get; set; }
        public string Merk { get; set; }
        public string Tipe { get; set; }
        public int? Tenor { get; set; }
        public decimal? Installment { get; set; }
        public string TipeAplikasiID { get; set; }
        public decimal? Pencairan { get; set; }
        public DateTime ApprovedDate { get; set; }
        public decimal? DPSetor { get; set; }
        public string NamaStnk { get; set; }
    }
}
