// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCasAcHeader
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// user yang menyetujui
        /// </summary>
        public string ApprovedBy { get; set; }
        /// <summary>
        /// tanggal disetujui
        /// </summary>
        public DateTime? ApprovedDate { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// nomor dokumen
        /// </summary>
        public string DocumentNo { get; set; }
        /// <summary>
        /// ID tipe foto
        /// </summary>
        public DateTime? DocumentDate { get; set; }
        /// <summary>
        /// ID foto
        /// </summary>
        public string Capacity { get; set; }
        /// <summary>
        /// kapasitas
        /// </summary>
        public string Capital { get; set; }
        /// <summary>
        /// karakter
        /// </summary>
        public string Character { get; set; }
        /// <summary>
        /// kondisi
        /// </summary>
        public string Condition { get; set; }
        /// <summary>
        /// jaminan
        /// </summary>
        public string Collateral { get; set; }
        /// <summary>
        /// analisa tambahan CMO
        /// </summary>
        public string CmoAdditionalAnalysis { get; set; }
        /// <summary>
        /// catatan kelebihan
        /// </summary>
        public string AdvantageNotes { get; set; }
        /// <summary>
        /// catatan kekurangan
        /// </summary>
        public string DeficiencyNotes { get; set; }
        /// <summary>
        /// status
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// pernyataan approval
        /// </summary>
        public string ApprovalStatement { get; set; }
        /// <summary>
        /// alasan RFA
        /// </summary>
        public string RfaReason { get; set; }
        /// <summary>
        /// kekuatan
        /// </summary>
        public string Strenght { get; set; }
        /// <summary>
        /// kelemahan
        /// </summary>
        public string Weakness { get; set; }
        /// <summary>
        /// peluang
        /// </summary>
        public string Opportunity { get; set; }
        /// <summary>
        /// ancaman
        /// </summary>
        public string Threat { get; set; }
        /// <summary>
        /// informasi saat menyimpan
        /// </summary>
        public string SavingInformation { get; set; }
    }
}