// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCasRepeatOrder
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// nomor NPP lama
        /// </summary>
        public string AgreementNumberOld { get; set; }
        /// <summary>
        /// deskripsi dari repeat order
        /// </summary>
        public string RepeatOrderDescription { get; set; }
        /// <summary>
        /// ID kategori repeat order
        /// </summary>
        public string RepeatOrderCategoryId { get; set; }
        /// <summary>
        /// ID keputusan repeat order
        /// </summary>
        public string RepeatOrderDecisionId { get; set; }
        /// <summary>
        /// ID sumber referensi repeat order
        /// </summary>
        public string RepeatOrderReferenceSourceId { get; set; }
        /// <summary>
        /// ID hubungan dengan pemohon repeat order
        /// </summary>
        public string RepeatOrderApplicantRelationId { get; set; }
        /// <summary>
        /// ID bank
        /// </summary>
        public string BankId { get; set; }
        /// <summary>
        /// nama akun
        /// </summary>
        public string AccountName { get; set; }
        /// <summary>
        /// nomor akun
        /// </summary>
        public string AccountNumber { get; set; }
        /// <summary>
        /// nomor telepon
        /// </summary>
        public string TelephoneNumber { get; set; }
        public string ReferenceSourceDesc { get; set; }

        public virtual TrCas Credit { get; set; }
    }
}