// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCasCorporateDocument
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// nama komisaris perusahaan
        /// </summary>
        public string CorporateCommisionerName { get; set; }
        /// <summary>
        /// nama direksi/direktur perusahaan
        /// </summary>
        public string CorporateDirectorName { get; set; }
        /// <summary>
        /// status perusahaan
        /// </summary>
        public string CorporateStatus { get; set; }
        /// <summary>
        /// ID bidang usaha perusahaan
        /// </summary>
        public int? CorporateIndustryId { get; set; }
        /// <summary>
        /// bidang usaha lain perusahaan
        /// </summary>
        public string CorporateOtherIndustry { get; set; }
        /// <summary>
        /// periode tahun lama usaha perusahaan
        /// </summary>
        public byte? CorporateYearPeriod { get; set; }
        /// <summary>
        /// periode bulan lama usaha perusahaan
        /// </summary>
        public byte? CorporateMonthPeriod { get; set; }
        /// <summary>
        /// jumlah karyawan perusahaan
        /// </summary>
        public decimal? CorporateNumberOfEmployee { get; set; }
        /// <summary>
        /// tipe debitur perusahaan
        /// </summary>
        public string CorporateDebiturType { get; set; }
        /// <summary>
        /// nomor telepon perusahaan
        /// </summary>
        public string CorporateTelephoneNumber { get; set; }
        /// <summary>
        /// nomor fax perusahaan
        /// </summary>
        public string CorporateFaxNumber { get; set; }
        /// <summary>
        /// website/situs perusahaan
        /// </summary>
        public string CorporateSite { get; set; }
        /// <summary>
        /// email perusahaan
        /// </summary>
        public string CorporateEmail { get; set; }
        /// <summary>
        /// nomor akta pendirian perusahaan
        /// </summary>
        public string FoundersDeedNumber { get; set; }
        /// <summary>
        /// tanggal akta pendirian perusahaan
        /// </summary>
        public DateTime? FoundersDeedDate { get; set; }
        /// <summary>
        /// nama notaris akta pendirian perusahaan
        /// </summary>
        public string FoundersNotaryName { get; set; }
        /// <summary>
        /// nomor akta pengurus terakhir perusahaan
        /// </summary>
        public string ManagementDeedNumber { get; set; }
        /// <summary>
        /// tanggal akta pengurus terakhir perusahaan
        /// </summary>
        public DateTime ManagementDeedDate { get; set; }
        /// <summary>
        /// nama notaris akta pengurus terakhir perusahaan
        /// </summary>
        public string ManagementNotaryName { get; set; }
        /// <summary>
        /// nomor KTP direksi/direktur
        /// </summary>
        public string DirectorIdentityNumber { get; set; }
        /// <summary>
        /// nomor KTP komisaris
        /// </summary>
        public string CommissionerIdentityNumber { get; set; }
        /// <summary>
        /// NPWP perusahaan
        /// </summary>
        public string CorporateTaxIdNumber { get; set; }
        /// <summary>
        /// NPWP direksi/direktur
        /// </summary>
        public string DirectorTaxIdNumber { get; set; }
        /// <summary>
        /// nomor SIUP
        /// </summary>
        public string SiupId { get; set; }
        /// <summary>
        /// tanggal terbit SIUP
        /// </summary>
        public DateTime SiupIssueDate { get; set; }
        /// <summary>
        /// tanggal jatuh tempo SIUP
        /// </summary>
        public DateTime SiupDueDate { get; set; }
        /// <summary>
        /// nomor TDP
        /// </summary>
        public string TdpId { get; set; }
        /// <summary>
        /// tanggal terbit TDP
        /// </summary>
        public DateTime TdpIssueDate { get; set; }
        /// <summary>
        /// tanggal jatuh tempo TDP
        /// </summary>
        public DateTime TdpDueDate { get; set; }
        /// <summary>
        /// indikator surat kelengkapan SITU atau izin gangguan
        /// </summary>
        public bool IsCompletenessLetter { get; set; }
        /// <summary>
        /// tanggal terbit surat kelengkapan
        /// </summary>
        public DateTime CompletenessLetterIssueDate { get; set; }
        /// <summary>
        /// tanggal jatuh tempo surat kelengkapan
        /// </summary>
        public DateTime CompletenessLetterDueDate { get; set; }

        public virtual TrCas Credit { get; set; }
    }
}