// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCaApprovalProgress
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID perusahaan
        /// </summary>
        public int CompanyId { get; set; }
        /// <summary>
        /// nomor CF
        /// </summary>
        public string CfNo { get; set; }
        /// <summary>
        /// ID skema approval
        /// </summary>
        public string ApprovalSchemeId { get; set; }
        /// <summary>
        /// ID tingkat approval
        /// </summary>
        public string ApprovalLevelId { get; set; }
        /// <summary>
        /// nomor induk karyawan
        /// </summary>
        public string Nik { get; set; }
        /// <summary>
        /// ID polis
        /// </summary>
        public string PolicyId { get; set; }
        /// <summary>
        /// indikator aktif atau tidak
        /// </summary>
        public bool LevelActive { get; set; }
        /// <summary>
        /// jumlah anggota minimum
        /// </summary>
        public int LevelQuorum { get; set; }
        /// <summary>
        /// tipe eskalasi
        /// </summary>
        public string LevelEscalationType { get; set; }
        /// <summary>
        /// hari eskalasi
        /// </summary>
        public byte? LevelEscalationDay { get; set; }
        /// <summary>
        /// tanggal request approval
        /// </summary>
        public DateTime? LevelRequestDate { get; set; }
        /// <summary>
        /// tanggal selesai approval
        /// </summary>
        public DateTime? LevelCompleteDate { get; set; }
        /// <summary>
        /// user wajib melakukan proses approval
        /// </summary>
        public bool UserMandatory { get; set; }
        /// <summary>
        /// tanggal user mengubah tipe status approval
        /// </summary>
        public DateTime? UserDtmStatusChanged { get; set; }
        /// <summary>
        /// tipe status approval user
        /// </summary>
        public string UserStatusType { get; set; }
        /// <summary>
        /// keterangan approval user
        /// </summary>
        public string UserKeteranganApproval { get; set; }
        /// <summary>
        /// ID tingkat approval selanjutnya
        /// </summary>
        public string NextApprovalLevelId { get; set; }
        /// <summary>
        /// media menyetujui
        /// </summary>
        public byte? MediaApprove { get; set; }
        /// <summary>
        /// indikator notifikasi atau tidak
        /// </summary>
        public bool IsNotification { get; set; }
    }
}