// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCaAccountMutation
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID mutasi rekening CA
        /// </summary>
        public long Id { get; set; }
        /// <summary>
        /// ID detail rekening CA
        /// </summary>
        public string AccountDetailId { get; set; }
        /// <summary>
        /// bulan mutasi
        /// </summary>
        public string MutationMonth { get; set; }
        /// <summary>
        /// tahun mutasi
        /// </summary>
        public string MutationYear { get; set; }
        /// <summary>
        /// total mutasi kredit
        /// </summary>
        public decimal? TotalCreditMutation { get; set; }
        /// <summary>
        /// total mutasi debit
        /// </summary>
        public decimal? TotalDebitMutation { get; set; }
        /// <summary>
        /// saldo akhir bulan
        /// </summary>
        public decimal? EndOfMonthBalance { get; set; }

        public virtual TrCaAccountDetail AccountDetail { get; set; }
    }
}