// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCasPhotoDetail
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public int Id { get; set; }
        public string CreditId { get; set; }
        public string PhotoTypeId { get; set; }
        public string Filename { get; set; }
        public string FilePath { get; set; }
        public string Status { get; set; }
        public string PhotoId { get; set; }
    }
}