// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCaPrintHistory
    {
        /// <summary>
        /// ID print history CA
        /// </summary>
        public long Id { get; set; }
        /// <summary>
        /// nomor CA
        /// </summary>
        public string CaNo { get; set; }
        /// <summary>
        /// user yang melakukan print
        /// </summary>
        public string PrintedBy { get; set; }
        /// <summary>
        /// tanggal print
        /// </summary>
        public DateTime? PrintedDate { get; set; }
        /// <summary>
        /// urutan
        /// </summary>
        public int? Sequence { get; set; }
    }
}