// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrCmInsurance
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        public string Acp { get; set; }
        /// <summary>
        /// tipe bayar asuransi
        /// </summary>
        public string InsTipeBayar { get; set; }
        /// <summary>
        /// model asuransi
        /// </summary>
        public int? InsModel { get; set; }
        /// <summary>
        /// TLO1 (menentukan nominal biaya proses)
        /// </summary>
        public bool? Tlo1 { get; set; }
        /// <summary>
        /// TLO2 (menentukan nominal biaya proses)
        /// </summary>
        public bool? Tlo2 { get; set; }
        /// <summary>
        /// TLO3 (menentukan nominal biaya proses)
        /// </summary>
        public bool? Tlo3 { get; set; }
        /// <summary>
        /// TLO4 (menentukan nominal biaya proses)
        /// </summary>
        public bool? Tlo4 { get; set; }
        /// <summary>
        /// TLO5 (menentukan nominal biaya proses)
        /// </summary>
        public bool? Tlo5 { get; set; }
        /// <summary>
        /// AllRisk1 (menentukan nominal biaya proses)
        /// </summary>
        public bool? AllRisk1 { get; set; }
        /// <summary>
        /// AllRisk2 (menentukan nominal biaya proses)
        /// </summary>
        public bool? AllRisk2 { get; set; }
        /// <summary>
        /// AllRisk3 (menentukan nominal biaya proses)
        /// </summary>
        public bool? AllRisk3 { get; set; }
        /// <summary>
        /// AllRisk4 (menentukan nominal biaya proses)
        /// </summary>
        public bool? AllRisk4 { get; set; }
        /// <summary>
        /// AllRisk5 (menentukan nominal biaya proses)
        /// </summary>
        public bool? AllRisk5 { get; set; }
        /// <summary>
        /// biaya kerugian
        /// </summary>
        public decimal? LossFee { get; set; }
        public decimal? Cpfee { get; set; }
        /// <summary>
        /// biaya polis
        /// </summary>
        public decimal? PolicyFee { get; set; }
        /// <summary>
        /// tahun kredit
        /// </summary>
        public int? TahunKredit { get; set; }
        /// <summary>
        /// tahun tunai
        /// </summary>
        public int? TahunTunai { get; set; }
        /// <summary>
        /// biaya kredit
        /// </summary>
        public decimal? KreditFee { get; set; }
        /// <summary>
        /// biaya tunai
        /// </summary>
        public decimal? TunaiFee { get; set; }
    }
}