// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrDealerOrderSourceTac
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// ID jabatan
        /// </summary>
        public int JobTitleId { get; set; }
        /// <summary>
        /// ID personel
        /// </summary>
        public int PersonelId { get; set; }
        /// <summary>
        /// nama personel
        /// </summary>
        public string PersonelName { get; set; }
        /// <summary>
        /// bunga refund TAC
        /// </summary>
        public decimal RateTacRefund { get; set; }
        /// <summary>
        /// nominal refund TAC
        /// </summary>
        public decimal AmountTacRefund { get; set; }
        /// <summary>
        /// nominal refund TAC setelah pajak
        /// </summary>
        public decimal AmountTacRefundAfterTax { get; set; }
        /// <summary>
        /// nomor rekening bank
        /// </summary>
        public string BankAccountNumber { get; set; }
        /// <summary>
        /// nama rekening bank
        /// </summary>
        public string BankAccountName { get; set; }

        public virtual TrNpp Credit { get; set; }
    }
}