// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrDealerOrderSourceHeader
    {
        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// nomor sumber order
        /// </summary>
        public string OrderSourceNo { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// kode dealer
        /// </summary>
        public string DealerCode { get; set; }
        /// <summary>
        /// status sumber order
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// tanggal disetujui
        /// </summary>
        public DateTime? ApprovedDate { get; set; }
        /// <summary>
        /// user yang menyetujui
        /// </summary>
        public string ApprovedBy { get; set; }
        /// <summary>
        /// deskripsi perubahan
        /// </summary>
        public string ChangesDesc { get; set; }

        public virtual TrNpp Credit { get; set; }
    }
}