// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrGenerateCode
    {
        public int Id { get; set; }
        public string CodeType { get; set; }
        public string PeriodYear { get; set; }
        public string PeriodMonth { get; set; }
        public string CodeFormat { get; set; }
        public int LastNumber { get; set; }
        public DateTime LastGenerateDate { get; set; }
    }
}