// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrHierarchyTransaction
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string TransId { get; set; }
        public string TransTypeId { get; set; }
        public DateTime? TransDate { get; set; }
        public string EmployeeId { get; set; }
        public string NextEmployeeId { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string SuperEmployeeId { get; set; }
        public int HierarchyTransId { get; set; }
        public string ReasonId { get; set; }
    }
}