// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrItems
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string CreditId { get; set; }
        public string ChasisNo { get; set; }
        public string MachineNo { get; set; }
        public string ItemColor { get; set; }
        public string KeyNo { get; set; }
        public string CarNoUmc { get; set; }

        public virtual TrNpp Credit { get; set; }
    }
}