// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrNppPrint
    {
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// indikator print PK atau tidak
        /// </summary>
        public bool IsPrintPk { get; set; }
        /// <summary>
        /// total berapa kali print PK
        /// </summary>
        public int SumOfPrintPk { get; set; }
        /// <summary>
        /// tanggal pertama kali print PK
        /// </summary>
        public DateTime? FirstPrintDatePk { get; set; }
        /// <summary>
        /// tanggal terakhir kali print PK
        /// </summary>
        public DateTime? LastPrintDatePk { get; set; }
        /// <summary>
        /// user yang pertama kali print PK
        /// </summary>
        public string FirstPrintByPk { get; set; }
        /// <summary>
        /// user yang terakhir kali print PK
        /// </summary>
        public string LastPrintByPk { get; set; }
        /// <summary>
        /// indikator print akad atau tidak
        /// </summary>
        public bool IsPrintAkad { get; set; }
        /// <summary>
        /// total berapa kali print akad
        /// </summary>
        public int SumOfPrintAkad { get; set; }
        /// <summary>
        /// tanggal pertama kali print akad
        /// </summary>
        public DateTime? FirstPrintDateAkad { get; set; }
        /// <summary>
        /// tanggal terakhir kali print akad
        /// </summary>
        public DateTime? LastPrintDateAkad { get; set; }
        /// <summary>
        /// user yang pertama kali print akad
        /// </summary>
        public string FirstPrintByAkad { get; set; }
        /// <summary>
        /// user yang terakhir kali print akad
        /// </summary>
        public string LastPrintByAkad { get; set; }
        /// <summary>
        /// indikator print fidusia atau tidak
        /// </summary>
        public bool IsPrintFiduciary { get; set; }
        /// <summary>
        /// total berapa kali print fidusia
        /// </summary>
        public int SumOfPrintFiduciary { get; set; }
        /// <summary>
        /// tanggal pertama kali print fidusia
        /// </summary>
        public DateTime? FirstPrintDateFiduciary { get; set; }
        /// <summary>
        /// tanggal terakhir kali print fidusia
        /// </summary>
        public DateTime? LastPrintDateFiduciary { get; set; }
        /// <summary>
        /// user yang pertama kali print fidusia
        /// </summary>
        public string FirstPrintByFiduciary { get; set; }
        /// <summary>
        /// user yang terakhir kali print fidusia
        /// </summary>
        public string LastPrintByFiduciary { get; set; }
        /// <summary>
        /// status kirim fidusia
        /// </summary>
        public string FiduciarySendStatus { get; set; }
        /// <summary>
        /// pengirim fidusia
        /// </summary>
        public string FiduciarySender { get; set; }
        /// <summary>
        /// tanggal kirim fidusia
        /// </summary>
        public DateTime? FiduciarySendDate { get; set; }
        /// <summary>
        /// status terima fidusia
        /// </summary>
        public string FiduciaryReceiveStatus { get; set; }
        /// <summary>
        /// penerima fidusia
        /// </summary>
        public string FiduciaryReceiver { get; set; }
        /// <summary>
        /// tanggal terima fidusia
        /// </summary>
        public DateTime? FiduciaryReceiveDate { get; set; }
        /// <summary>
        /// status penyelesaian
        /// </summary>
        public string CompleteStatus { get; set; }
        /// <summary>
        /// tanggal cek penyelesaian
        /// </summary>
        public DateTime? CompleteCheckDate { get; set; }
        /// <summary>
        /// nama cek penyelesaian
        /// </summary>
        public string CompleteCheckName { get; set; }
        /// <summary>
        /// status kirim notaris
        /// </summary>
        public string NotarySendStatus { get; set; }
        /// <summary>
        /// pengirim notaris
        /// </summary>
        public string NotarySender { get; set; }
        /// <summary>
        /// tanggal kirim notaris
        /// </summary>
        public DateTime? NotarySendDate { get; set; }
        /// <summary>
        /// status terima notaris
        /// </summary>
        public string NotaryReceiveStatus { get; set; }
        /// <summary>
        /// penerima notaris
        /// </summary>
        public string NotaryReceiver { get; set; }
        /// <summary>
        /// tanggal terima notaris
        /// </summary>
        public DateTime? NotaryReceiveDate { get; set; }
        /// <summary>
        /// indikator upload atau tidak
        /// </summary>
        public int? IsUpload { get; set; }
        /// <summary>
        /// status revisi fidusia
        /// </summary>
        public string FiduciaryRevisionStatus { get; set; }
        /// <summary>
        /// permintaan revisi fidusia
        /// </summary>
        public string FiduciaryRevisionRequest { get; set; }
        /// <summary>
        /// tanggal revisi fidusia
        /// </summary>
        public DateTime? FiduciaryRevisionDate { get; set; }
        /// <summary>
        /// status pengirim revisi fidusia
        /// </summary>
        public string FiduciaryRevisionSenderStatus { get; set; }
        /// <summary>
        /// pengirim revisi fidusia
        /// </summary>
        public string FiduciaryRevisionSender { get; set; }
        /// <summary>
        /// tanggal pengirim revisi fidusia
        /// </summary>
        public DateTime? FiduciaryRevisionSenderDate { get; set; }

        public virtual TrNpp Credit { get; set; }
    }
}