// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrNpp
    {
        public TrNpp()
        {
            TrDealerOrderSourceHeader = new HashSet<TrDealerOrderSourceHeader>();
            TrDealerOrderSourceTac = new HashSet<TrDealerOrderSourceTac>();
            TrDealerOrderSourceThirdParty = new HashSet<TrDealerOrderSourceThirdParty>();
        }

        /// <summary>
        /// user yang membuat master data
        /// </summary>
        public string CreatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu pembuatan master data
        /// </summary>
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// user yang mengubah master data
        /// </summary>
        public string LastUpdatedBy { get; set; }
        /// <summary>
        /// tanggal &amp; waktu perubahan master data
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }
        /// <summary>
        /// user yang menyetujui
        /// </summary>
        public string ApproveBy { get; set; }
        /// <summary>
        /// tanggal disetujui
        /// </summary>
        public DateTime? ApproveDate { get; set; }
        /// <summary>
        /// ID kredit
        /// </summary>
        public string CreditId { get; set; }
        /// <summary>
        /// tanggal NPP
        /// </summary>
        public DateTime? AgreementDate { get; set; }
        /// <summary>
        /// ID perusahaan
        /// </summary>
        public string CompanyId { get; set; }
        /// <summary>
        /// ID cabang
        /// </summary>
        public string BranchId { get; set; }
        /// <summary>
        /// tanggal tagihan diterima
        /// </summary>
        public DateTime? BillReceivedDate { get; set; }
        /// <summary>
        /// tanggal tanda terima tagihan
        /// </summary>
        public DateTime? BillReceiptDate { get; set; }
        /// <summary>
        /// nomor tanda terima uang muka
        /// </summary>
        public string DownPaymentReceiptNo { get; set; }
        /// <summary>
        /// tanggal tanda terima uang muka
        /// </summary>
        public DateTime? DownPaymentReceiptDate { get; set; }
        /// <summary>
        /// nomor resi
        /// </summary>
        public string ReceiptNo { get; set; }
        /// <summary>
        /// tanggal resi
        /// </summary>
        public DateTime? ReceiptDate { get; set; }
        /// <summary>
        /// nomor surat BPKB
        /// </summary>
        public string BpkbLetterNo { get; set; }
        /// <summary>
        /// tanggal surat BPKB
        /// </summary>
        public DateTime? BpkbLetterDate { get; set; }
        /// <summary>
        /// nomor BAST
        /// </summary>
        public string BastNo { get; set; }
        /// <summary>
        /// tanggal BAST
        /// </summary>
        public DateTime? BastDate { get; set; }
        /// <summary>
        /// tanggal angsuran
        /// </summary>
        public DateTime? InstallmentDate { get; set; }
        /// <summary>
        /// ID referensi bank
        /// </summary>
        public int BankReferenceId { get; set; }
        /// <summary>
        /// status NPP
        /// </summary>
        public string AgreementStatus { get; set; }
        /// <summary>
        /// tanggal angsuran konsumen
        /// </summary>
        public DateTime? ConsumenInstallmentDate { get; set; }
        /// <summary>
        /// persenan NFA
        /// </summary>
        public decimal? NfaPercent { get; set; }
        /// <summary>
        /// indikator plafon atau tidak
        /// </summary>
        public bool IsPlafon { get; set; }
        /// <summary>
        /// nilai NPP
        /// </summary>
        public decimal? AgreementValue { get; set; }
        /// <summary>
        /// biaya perkiraan asuransi
        /// </summary>
        public decimal? EstimatedInsuranceCost { get; set; }
        /// <summary>
        /// periode cakupan asuransi
        /// </summary>
        public string InsuranceCoveragePeriod { get; set; }
        /// <summary>
        /// nilai AP lainnya
        /// </summary>
        public decimal? OtherApValue { get; set; }
        /// <summary>
        /// tagihan asuransi berkala
        /// </summary>
        public string InsuranceBillingPeriodical { get; set; }
        /// <summary>
        /// ID sub referensi bank
        /// </summary>
        public int BankReferenceSubId { get; set; }
        /// <summary>
        /// tipe pencairan UMC
        /// </summary>
        public string DisbursalTypeUmc { get; set; }
        /// <summary>
        /// insentif tipe pencairan UMC
        /// </summary>
        public string DisbursalTypeUmcIncentive { get; set; }
        /// <summary>
        /// nominal insentif
        /// </summary>
        public decimal? IncentiveNominal { get; set; }
        /// <summary>
        /// ID asuransi
        /// </summary>
        public string InsuranceId { get; set; }

        public virtual TrItems TrItems { get; set; }
        public virtual TrNppPrint TrNppPrint { get; set; }
        public virtual ICollection<TrDealerOrderSourceHeader> TrDealerOrderSourceHeader { get; set; }
        public virtual ICollection<TrDealerOrderSourceTac> TrDealerOrderSourceTac { get; set; }
        public virtual ICollection<TrDealerOrderSourceThirdParty> TrDealerOrderSourceThirdParty { get; set; }
    }
}