// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class TrSendPoLog
    {
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int Id { get; set; }
        public string PoNo { get; set; }
        public string CreditId { get; set; }
        public DateTime? CreditDate { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string ItemId { get; set; }
        public string ItemMerkId { get; set; }
        public string ItemMerkTypeId { get; set; }
        public string AccountReceiveable { get; set; }
        public decimal? AssetCost { get; set; }
        public decimal? GrossDownPayment { get; set; }
        public decimal? NettDownPayment { get; set; }
        public byte? Tenor { get; set; }
        public decimal? AmountInstallment { get; set; }
        public double? EffectiveRate { get; set; }
        public double? FlatRate { get; set; }
        public decimal? JmlPembiayaan { get; set; }
        public string DealerCode { get; set; }
        public string Email { get; set; }
    }
}