// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Acquisition.AcquisitionModel
{
    public partial class VwAgreementOld
    {
        public string LesseeId { get; set; }
        public string NppNo { get; set; }
        public string ItemMerk { get; set; }
        public string ItemTypeName { get; set; }
    }
}