// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.Models
{
    public partial class LogError
    {
        public string UserName { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorState { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorProcedure { get; set; }
        public DateTime ErrorDateTime { get; set; }
    }
}