// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.Models
{
    public partial class sp_get_risk_categoryResult
    {
        public string created_by { get; set; }
        public DateTime? created_on { get; set; }
        public string last_updated_by { get; set; }
        public DateTime? last_updated_on { get; set; }
        public int risk_id { get; set; }
        public int risk_parameter_id { get; set; }
        public int risk_category_id { get; set; }
        public decimal start_point { get; set; }
        public decimal end_point { get; set; }
        public bool is_active { get; set; }
    }
}
