// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.Models
{
    public partial class TesTrCasAcheader
    {
        public string Casid { get; set; }
        public string DocNo { get; set; }
        public DateTime? DocDate { get; set; }
        public string Capacity { get; set; }
        public string Capital { get; set; }
        public string Character { get; set; }
        public string Condition { get; set; }
        public string Collateral { get; set; }
        public string AnalisaTambahanCmo { get; set; }
        public string NotesKelebihan { get; set; }
        public string NotesKekurangan { get; set; }
        public string Status { get; set; }
        public string KeteranganApproval { get; set; }
        public string AlasanRfa { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public string Strenght { get; set; }
        public string Weakness { get; set; }
        public string Opportunity { get; set; }
        public string Threat { get; set; }
        public string KetTabungan { get; set; }
    }
}