// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

<<<<<<<< HEAD:FINCORE.LIBRARY.DTO/EntityFramework/Masters/MastersModels/MsIncentiveBy.cs
namespace FINCORE.LIBRARY.DTO.EntityFramwork.Masters.MastersModels
{
    public partial class MsIncentiveBy
========
namespace FINCORE.LIBRARY.DTO.Models
{
    public partial class TesTrCasAcdetail
<<<<<<< HEAD
>>>>>>>> 3056edc6ef946ac0b25710ae279e1f1d6484c583:FINCORE.LIBRARY.DTO/Models/TesTrCasAcdetail.cs
=======
>>>>>>>> origin/Development:FINCORE.LIBRARY.DTO/Models/TesTrCasAcdetail.cs
>>>>>>> e177c7b0093e0b583c223fc7677e850e582e35a2
    {
        public string Casid { get; set; }
        public string DocNo { get; set; }
        public string PhotoTypeId { get; set; }
        public string PhotoId { get; set; }
        public string Filename { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
<<<<<<<< HEAD:FINCORE.LIBRARY.DTO/EntityFramework/Masters/MastersModels/MsIncentiveBy.cs
        public string IncentiveById { get; set; }
        public string IncentiveByName { get; set; }
        public bool IsActive { get; set; }
========
<<<<<<< HEAD
>>>>>>>> 3056edc6ef946ac0b25710ae279e1f1d6484c583:FINCORE.LIBRARY.DTO/Models/TesTrCasAcdetail.cs
=======
>>>>>>>> origin/Development:FINCORE.LIBRARY.DTO/Models/TesTrCasAcdetail.cs
>>>>>>> e177c7b0093e0b583c223fc7677e850e582e35a2
    }
}