// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINCORE.LIBRARY.DTO.Models
{
    public partial class TrBpkbTest1
    {
        public string Bpkbno { get; set; }
        public string BranchId { get; set; }
        public string AgreementNumber { get; set; }
        public DateTime? BpkbdateIn { get; set; }
        public DateTime? Bpkbdate { get; set; }
        public string FakturNo { get; set; }
        public DateTime? FakturDate { get; set; }
        public string Bpkbstatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LocationId { get; set; }
        public string SerialNo { get; set; }
        public string PoliceNo { get; set; }
    }
}