// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FINCORE.LIBRARY.DTO.EntityFramework.Payment.PaymentModel
{
    public partial class sp_get_pagination_cashier_sessionResult
    {
        public string SessionId { get; set; }
        public string UserId { get; set; }
        public string BranchId { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime? CloseDate { get; set; }
        public decimal? CurrentAmount { get; set; }
        public decimal? CashAmount { get; set; }
    }
}
